# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ main ]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test
        
  build:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-artifact:
    runs-on: ubuntu-latest
    needs: [build, unit-test]
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven Settings for deploy
        uses: s4u/maven-settings-action@v2.1.1
      - name: Publish package
      ##  run: mvn --batch-mode deploy
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAMEGITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
       ## run: mvn --settings settings.xml --file pom.xml deploy
       ## run: mvn clean source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -Dmaven.install.skip=true -DdeplyAtEnd=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/jesusrh12/ffm-ne-back-jv-lib-commons'
        run: mvn source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/bsneyder/mavenprueba'
        
  deployregistry:
    name: deploy to registry
    runs-on: ubuntu-latest
    needs: [build, unit-test, publish-artifact]
    steps:
    - uses: actions/checkout@main
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.USERNAMEDOCKER }}
        password: ${{ secrets.PASSWORD_DOCKERHUB }}
        repository: ${{ github.repository }}
        tag_with_sha: true
        tags: ${{ github.sha }}
      

      
        
       


        
